### ISSUE TITLE
06 .md formatting and tables

### ISSUE THREAD

**Issue by tmorrell** [datacarpentry/python-ecology-lesson#174]
Episode 6 has extra blank lines and odd table formatting.  It looks like the markdown file was transformed from the jupyter notebook version.  Are we treating the markdown version of the file as the official course content?

Also, I think we can delete 06-visualization-ggplot-R.ipynb

**Comment by wrightaprilm** [comment]
It was transformed from the ipynb. We are treating the Md as the course content, since the website renders from it, the notebook is mostly there in case instructors want to use it for purposes of visualizations, since the commands get quite long. 

I think what I might do is cut down the length of the tables. Would that handle the issue here?

**Comment by tmorrell** [comment]
Yup.  I can also try to convert the tables to markdown styling if you'd like.

**Comment by wrightaprilm** [comment]
OK, I truncated those tables. Take a look at them when you have a chance?
