### ISSUE TITLE
add link to the data in the 'starting with data' lesson

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/python-ecology-lesson#24]
There is not currently a link to the data used in the lesson, in the '01-starting-with-data' lesson.  We should add a link to the data. 

That link is currently in the repo in https://github.com/datacarpentry/python-ecology/tree/gh-pages/data

When we switch over to the FigShare database as in https://github.com/datacarpentry/python-ecology/issues/23 we can update the link.

**Comment by hlapp** [comment]
Changing the data link to Figshare still needs to happen, the merge of #25 (see 9ec7fc93e6bc4e2bf3769e91d41b283d50c055f2) didn't address that.

**Comment by tracykteal** [comment]
It's now addressed in https://github.com/datacarpentry/python-ecology/pull/34 and should now be fixed

**Comment by mboisson** [comment]
I am currently going through the lesson to teach it tomorrow. The links provided are completely out of phase with the content of the lessons themselves. For example, lesson on automating data refers to a "data" folder, which does not exist (only 2 files are provided for download, rather than a whole directory). It also supposedly contains the files "plots.csv", "portal_mammals.sqlite", "species.csv", "surveys.csv", etc. In previous lessons some of those files are used, but downloaded each time from figshare. 

It would be best if a single archive was downloaded, and if all the lessons would use the data that is contained within the archive.

**Comment by ethanwhite** [comment]
@mboisson - I'm not actively involved in this lesson, but for the data itself is now centrally stored on figshare: https://figshare.com/articles/Portal_Project_Teaching_Database/1314459. If you think an archive with a particular set of files would be a useful addition please open an issues at https://github.com/weecology/portal-teachingdb. Thanks.

**Comment by mboisson** [comment]
From what I can see, the following file structures is what is needed for the Python Ecology Lesson : [python-ecology]$ ls data/
portal_mammals.sqlite	species.csv		surveys.csv

The biggest part of the work however is to modify the lesson so that it uses those files rather than downloading the single files every time. It is more of a work on the Data Carpentry lesson than work on the organization of the files in Figshare.

**Comment by justbennet** [comment]
Maxime, you get a couple of extra files, but the Download all button on the figshare site links to a .zip of everything.  Does that help any?

You said:  "The biggest part of the work however is to modify the lesson so that it uses those files rather than downloading the single files every time."  Do you mean, modify the lesson so the pd.read_csv() commands refer to the local files rather than to URLs?

**Comment by mboisson** [comment]
Yes indeed, this is what I am referring to. In my opinion, a lesson should be self-contained. You download all of the data in one step, and then always work with these files.

**Comment by justbennet** [comment]
Maxime, I submitted a pull request to change pd.read_csv('URL') to pd.read_csv('FILE').

**Comment by justbennet** [comment]
The information about getting the data and what's in it has got a bit muddled, I think.  I propose that the following changes be made to the current material.

Reorder the sections at the beginning of the lesson.  Currently, there is information about the data, then downloading, then libraries, then information about the data is repeated almost verbatim in the lesson overview.  I propose the following changes.

I think the lesson could lead off with About Libraries (I would add a sentence here explaining also that libraries are sophisticated code reuse, which we encourage).  Next would be the short section on how to download just the surveys.csv file.  A reference could be added back to the main index page where the full data URL is given.

With libraries and downloading out of the way, Presentation of the Survey Data section would appear next.  I would move the chunk from Lesson Overview that shows the first bit of data into that section, so that the Lesson Overview can just layout the tasks that will be completed in the lesson.

I think that would flow better, even if it delays getting the crux of the lesson.  I'm happy to make those changes, but having just muddled a pull request, I'd ask for some assistance getting it here.

Alternately, I think that moving the data listing into Presentation of the Survey Data would make the overview smoother, and perhaps the overview should be moved to the very top, if people think it should really be the lead item.

**Comment by hugobowne** [comment]
I am going through this lesson in some detail and have noticed that the [Plotting with ggplot lesson](http://www.datacarpentry.org/python-ecology-lesson/06-visualization-ggplot-python) makes use of a dataset 'surveys_complete.csv', which is in a different directory. is there a reason for this? if not, it makes sense to put them all together.

**Comment by mkuzak** [comment]
I'm in favour of moving it to `data` directory, where other date files are located. @djinnome you contributed the lesson, can you comment on that?

**Comment by tracykteal** [comment]
@wrightaprilm @qjcg do you know if where the data is has been addressed now that things are in FigShare?

**Comment by willingc** [comment]
@tracykteal This looks like it can be closed since the Data section on the main page http://www.datacarpentry.org/python-ecology-lesson/ looks complete with download links for CSV files and FigShare source.

**Comment by wrightaprilm** [comment]
Fixed. Closing.
