### ISSUE TITLE
from @crocodoyle: Pyplot tutorial should close plots

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/python-ecology-lesson#277]
In lesson 7, (http://www.datacarpentry.org/python-ecology-lesson/07-putting-it-all-together/), none of the examples close pyplot. This isn't a problem if only following the examples, but very important if you're creating figures in loops or creating lots of plots.

initially submited at: datacarpentry/datacarpentry.github.io#430

**Comment by maxim-belkin** [comment]
+1 for adding this to the lesson

**Comment by stijnvanhoey** [comment]
I do think this intersects with the comments about the  #254 and the main discussion about rewriting the *putting-it-all-together* lesson. 

With regard to the plotting, it would maybe be beneficial to learn people how make Pandas based plotting using the object oriented approach of matplotlib instead of the `plt.***` approach of plotting (and requirement of closing plots). e.g.
```
# create object
fig, ax = plt.subplots()

# add something on the ax directly from pandas
df.plot(..., ax = ax,..)

# do further adjustments with matplotlib syntax
ax.set_title(...
```
As such, it connects with the previous lessons and the plots made there (using Pandas) and this can be applied to the `plotnine` lesson as well (these are also matplotlib objects). As it is now, it feels like a whole new concept in a lesson called *putting-it-all-together*...

**Comment by btovar** [comment]
Closing in favor of #254
