### ISSUE TITLE
Changed variable naming 'plot_id' to 'site_id' introduced inconsistencies

### ISSUE THREAD

**Issue by katrintirok** [datacarpentry/python-ecology-lesson#279]
The data on the GitHub repository are now inconsistent with the data on figshare, some episodes still refer to figshare. Using 'site_id' instead of 'plot_id' also introduces inconsistency with the other lessons (spreadsheets, openRefine, Sql, R).

Go back to 'plot_id' (for now)?

**Comment by astrochun** [comment]
Experience the same issue during Instructor workshop.

**Comment by maxim-belkin** [comment]
@astrochun can you check if changes in datacarpentry/python-ecology-lesson#/281 solve this for you?

**Comment by astrochun** [comment]
@maxim-belkin: The issue is the the instruction here: http://www.datacarpentry.org/python-ecology-lesson/01-starting-with-data/

Refers to the following file for the data: https://ndownloader.figshare.com/files/2292172

I did not download the data from git, so the fix that was implemented is not being used unless you update the figshare file or you provide the updated link.

**Comment by wrightaprilm** [comment]
Right, the language issues should be solved by #281. I completely forgot to merge that one, but it's in now. I've opened #283 to change self-hosted versions of the figshare files back.
