### ISSUE TITLE
Add instructions for saving figures to Matplotlib lesson

### ISSUE THREAD

**Issue by gaurav** [datacarpentry/python-ecology-lesson#293]
I like that the [*Making Plots With ggplot* lesson](http://www.datacarpentry.org/python-ecology-lesson/07-visualization-ggplot-python/index.html) includes instructions on saving the generated plot, which provides an output that students can incorporate into their own work. I think we should extend the [*Data Ingest and Visualization - Matplotlib and Pandas* lesson](http://www.datacarpentry.org/python-ecology-lesson/08-putting-it-all-together/index.html) to include using [`matplotlib.pyplot.savefig`](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.savefig.html) to save those figures as well.

**Comment by trallard** [comment]
Hi! 

I like the idea. Although there have been other discussions about adding plt.close( ) or substituting the use of matplotlib for pandas.plot( )  

#277 

Although I suppose for completion and since this is not too big a contribution would you like to add this to the lesson? 

Or would you prefer me marking this as up for grabs?

**Comment by gaurav** [comment]
Sorry for my slow reply! I'm not familiar enough with PyPlot and Jupyter to write about the best practice for exporting figures from it, but I'm glad you've posted this as a "help wanted" post! If nobody's tackled this in a month or two, let me know and I'll take a bash at it!
