### ISSUE TITLE
Lesson Contribution - Felesia A. Stukes

### ISSUE THREAD

**Issue by sheraaron** [datacarpentry/python-ecology-lesson#329]
The recommended change is highlighted below.

Starting in the same spot

To help the lesson run smoothly, let's ensure everyone is in the same directory. This should help us avoid path and file name issues. At this time please navigate to the workshop directory. If you working in Jupyter Notebook (formerly called IPython Notebook) be sure that you start your notebook in the workshop directory.

**Comment by wrightaprilm** [comment]
We've always been a bit vague on how to start the Jupyter Notebook, mainly due to the differences between Windows and Mac.  Was Felesia looking to insert this language in the setup, or instructor's guide? I'm going to bring this up in the maintainer's meeting today; since there are now more Data Carpentry Python lessons being incubated, perhaps there ought to be a uniform set of materials we all draw this language from.
