### ISSUE TITLE
June 2019 Lesson Release checklist

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/python-ecology-lesson#373]
If your Maintainer team has decided not to participate in the [June 2019 lesson release](https://carpentries.topicbox.com/groups/maintainers/T61c75ac1a8a89538/timeline-and-process-for-june-lesson-release), please close this issue.

To have this lesson included in the 18 June 2019 release, please confirm that the following items are true:

- [x] Example code chunks run as expected
- [x] Challenges / exercises run as expected
- [x] Challenge / exercise solutions are correct
- [x] Call out boxes (exercises, discussions, tips, etc) render correctly
- [x] A schedule appears on the lesson homepage (e.g. not “00:00”)
- [x] Each episode includes learning objectives
- [x] Each episode includes questions
- [x] Each episode includes key points
- [x] Setup instructions are up-to-date, correct, clear, and complete
- [x] File structure is clean (e.g. delete deprecated files, insure filenames are consistent)
- [x] Some Instructor notes are provided
- [x] Lesson links work as expected

When all checkboxes above are completed, this lesson will be added to the 18 June lesson release. Please leave a comment on carpentries/lesson-infrastructure#26 or contact Erin Becker with questions (ebecker@carpentries.org).

**Comment by ErinBecker** [comment]
Hi @wrightaprilm @maxim-belkin and @trallard - Just confirming that you're still planning on including your lesson in the June 2019 release. We'll be putting out a blog post tomorrow inviting contributors to work on issues that have been tagged as part of the release milestone, so if there are specific issues you're looking for community help with, please add them to that milestone. I'll go ahead and do that too for the "help-wanted" issues. Please let me know if you have any questions!

**Comment by wrightaprilm** [comment]
Sounds good. It looks like all the help-wanteds are in the milestone, so that's good.

**Comment by ErinBecker** [comment]
Hey Maintainers - just checking in to see if you're still planning on joining the release this month. We're asking that all lessons have completed the checklist by [Tuesday, 4 June, Anywhere on Earth time](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20190604T235959&p1=3399) in order to be included in the release. Please let me and @fmichonneau know if you have any questions or are running into any technical issues with preparing your lesson.

**Comment by ErinBecker** [comment]
Awesome work @wrightaprilm @maxim-belkin @trallard and everyone else who contributed! This is just a quick message confirming that this lesson will be included in the release that @fmichonneau and I are preparing this week. The release is scheduled to go through on the 18th and to be announced to the community on the 24th. Please let us know if you have any questions! And congratulations again!

**Comment by fmichonneau** [comment]
lesson released! :tada: https://doi.org/10.5281/zenodo.3264812

**Comment by wrightaprilm** [comment]
Hey all, how exciting!

It does look like something went a little funny in the authors/editors import. The former maintainers are listed as editors, but not the current ones. Likewise, it looks like the contributors list didn't update since the 2017 release. I'm a little jam-packed today (hello, returning after conferencing!), but I might have some time in the afternoon (US-Central) if my intervention is needed.

**Comment by ErinBecker** [comment]
Thanks for letting us know about the issue @wrightaprilm. We're looking into this right now.

**Comment by ErinBecker** [comment]
Thanks again for taking a look at the release and noticing the problem @wrightaprilm. @fmichonneau has re-done the release with the correct set of contributors and Maintainers, and it should be correct now! Here's the new doi: https://doi.org/10.5281/zenodo.3265185.

**Comment by wrightaprilm** [comment]
It looks good to me! Thanks so much for promptly getting on this.
