### ISSUE TITLE
Typo in Lesson 3 

### ISSUE THREAD

**Issue by marketneutral** [datacarpentry/python-ecology-lesson#443]
Hello, I am using this lesson to teach introductory Python and data analysis to some of my colleagues and it's great! Thank you!

I noticed a typo in [Lesson 3: Indexing, Slicing and Subsetting DataFrames in Python ](https://datacarpentry.org/python-ecology-lesson/03-index-slice-subset/index.html)

![image](https://user-images.githubusercontent.com/16124573/73110383-3320d500-3ed4-11ea-86d6-4194edcd7280.png)

"This means that the first element in an object is located at position 1." should read "This means that the first element in an object is located at position **0**."

**Comment by maxim-belkin** [comment]
Hi Jonathan. Thanks for creating this issue. This was a rather interesting bug (solved in 79b646b by @jackVanish) caused by Markdown. The paragraph had correct information:

```
Let's remind ourselves that Python uses 0-based                                                         
indexing. This means that the first element in an object is located at position                         
0. This is different from other tools like R and Matlab that index elements                           
within objects starting at 1. 
```

However, because that "0." was the first thing on the (third) line, Markdown assumed that this was the beginning of a numbered HTML list and rendered it as one, using 1 as its first index. @jackVanish fixed that by encapsulating that 0 in backticks so that Markdown would no longer think that this is a numbered list.

Again, thank you for creating this issue and for the kind words!

Maxim
