### ISSUE TITLE
Need jump lists (anchors) for headings

### ISSUE THREAD

**Issue by annajiat** [datacarpentry/python-ecology-lesson#503]
@zkamvar
We need to update style for this lesson so that jump lists (anchors for different sections) becomes automatically available for different levels of headings.

**Comment by maxim-belkin** [comment]
I can take care of this, Annajiat.

**Comment by annajiat** [comment]
Great, thanks @maxim-belkin

**Comment by maxim-belkin** [comment]
No worries! Thanks for reminding me to take care of this. I've synced the lesson style files with carpentries/styles in d285ec4 and anchor links are now automatically added to all HTML headings.

**Comment by maxim-belkin** [comment]
I have a vague recollection that @fmichonneau documented this process somewhere but it's not that difficult so I can briefly describe it here:

1. Navigate to the lesson directory on your computer, e.g.:
   ```
   cd /path/to/datacarpentry/lesson
   ```
2. Add carpentries/styles repo as a remote:
   ```
   git remote add styles-repo https://github.com/carpentries/styles.git
   git config --local remote.styles-repo.tagOpt --no-tags
   git fetch styles-repo
   ```
3. Merge the `gh-pages` branch of the carpentries/styles repo into the `gh-pages` branch of the lesson repo:
   ```
   git merge -m "Sync style files with carpentries/styles" styles-repo/gh-pages
   ```
You might have to resolve Git conflicts here.
4. Push updated `gh-pages` branch to the lesson repository:
   ```
   git push https://github.com/datacarpentry/lesson gh-pages
   ```

IIRC, @fmichonneau does this in a separate branch and then submits a PR to merge that branch.

**Comment by zkamvar** [comment]
Thank you for taking care of this, @maxim-belkin. 

@annajiat, regarding the documentation, we created the https://github.com/carpentries/maintainer-resources repository in 2020 to store the meeting minutes and any potentially useful resources for maintainers but were not so great at advertising it.

The process for updating to the latest styles is here:

https://github.com/carpentries/maintainer-resources/blob/main/FLIGHT_RULES.md#update-styles

FWIW, François and I both use the branch-and-PR flow for this so that it's easier to recover when things go sideways. 

I apologise for not getting to the other issues you flagged me in... it's been a long week 😞
