### ISSUE TITLE
Lesson links are broken

### ISSUE THREAD

**Issue by thomasballinger** [datacarpentry/python-ecology-lesson#58]
Both the link in the GitHub description (http://datacarpentry.github.io/python-ecology) and the link at http://www.datacarpentry.org/lessons/#ecology-workshop (https://datacarpentry.github.io/python-ecology-lesson/) are broken for me.

**Comment by qjcg** [comment]
This repo was recently renamed from "python-ecology" to "python-ecology-lesson", which is _part of_ the cause for the broken link.

The other part of the cause seems to be that, on the DataCarpentry lesson links page, [an HTTPS link](https://datacarpentry.github.io/python-ecology-lesson/) is used, and results for a timeout for me as well. Using [an HTTP link](http://datacarpentry.github.io/python-ecology-lesson/) works fine. Requests to https://datacarpentry.github.io return an [HTTP 301 redirect](https://en.wikipedia.org/wiki/HTTP_301) towards www.datacarpentry.org, which does not appear to support HTTPS currently.

The permissions I have as a lesson maintainer ("write" permissions as opposed to "admin" permissions in terms of [GitHub's repo permission levels](https://help.github.com/articles/repository-permission-levels-for-an-organization/)) don't include "changing repository settings", which governs access to the "Edit" button next to the short description at the top of the [main repo page](https://github.com/datacarpentry/python-ecology-lesson/), so the other maintainers and I are unable to fix the URL there as things stand.

The **quick fix** would be for one of the repository owners to fix the URL at the top of this repo (python-ecology -> python-ecology-lesson), as well as change the links on the lesson links page to use HTTP-only links for now, or alternatively keep the HTTPS links on the lesson links page and disable https://datacarpentry.github.io from redirecting to www.datacarpentry.org.

The **long-term fix** would be to obtain and use a TLS certificate for datacarpentry.org. [Let's encrypt](https://letsencrypt.org) ([see also](https://en.wikipedia.org/wiki/Let's_Encrypt)) provides high-quality free TLS certificates.

CC: @tracykteal, @maneesha

**Comment by tracykteal** [comment]
Thanks, I fixed the URL on the top of they python-ecology-lesson repo. The problem with the links from the 'lessons' website was indeed the https rather than http, so I changed it there to use http instead. I also put in a redirect from www.datacarpentry.org/python-ecology to www.datacarpentry.org/python-ecology-lesson

Hopefully that should have fixed all the links, but please re-open this issue if not
