### ISSUE TITLE
Refer to current version of Python 

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/python-ecology-lesson#588]
### How could the content be improved?

In the [installation section](https://datacarpentry.org/python-ecology-lesson/#installing-python-using-anaconda) we say to use any Python 3.x version, and that 3.6 is fine.  We should now be on 3.8+ as 3.7 hit EOL in June 2023.  

### Which part of the content does your suggestion apply to?

https://datacarpentry.org/python-ecology-lesson/#installing-python-using-anaconda

**Comment by quist00** [comment]
I think we should bump the minimum recommendation to at least 3.10, which has 2.5 years until EOL. Also I think including the EOL date and just refer to it as the end of security updates, so that way maintainers don't need to adjust it for a long while and it will be obvious then when it will be out of date and needs to be updated more pro-actively rather than relying on someone catching it like you did. :)
