### ISSUE TITLE
Challenges are not always clear

### ISSUE THREAD

**Issue by ostueker** [datacarpentry/python-ecology-lesson#73]
I'm just working myself through this lesson, as I haven't worked with pandas so far and I found that for most of the challenges, it is not clear to me which result is expected.

Especially for challenges that ask to generate a plot, it would be really helpful if a PNG of the desired plot would be added to the challenge.  

I wanted to help adding solutions to the challenges to the `INSTRUCTORS.md` but often it is not clear to me what the person who has designed the challenge had in mind.

**Comment by wrightaprilm** [comment]
I agree - the creation of an Instructor's Guide fell by the wayside with a lot of the Data Carpentry lessons. Since, for some of the challenges, it can be unclear what the desired output is, I think the best way forward is to make a pull requests to the guide, individually for each solution/answer. That way, we can take a look, and if there are multiple possible solutions, I (or someone else) can add those in and do the merge. 

Thanks for bringing this to our attention - and sorry for my late reply. Summer travel season strikes again!

**Comment by tracykteal** [comment]
The challenge solutions are now in the instructors guide. Hooray! Is there more to do here though?

**Comment by wrightaprilm** [comment]
I believe #171 and #162 close these. Thanks to @tmorrell
