### ISSUE TITLE
No schedule in the lesson

### ISSUE THREAD

**Issue by barrachri** [datacarpentry/python-ecology-lesson#91]
I was checking the lesson for the schedule, but I didn't find it.

Is there a plan to add it ?

**Comment by wrightaprilm** [comment]
Sorry I'm so late getting back on this. When you say schedule, do you mean in the sense of [the SWC lessons?](http://swcarpentry.github.io/python-novice-inflammation/)

**Comment by barrachri** [comment]
Hi, yes, as the swc lessons.

**Comment by wrightaprilm** [comment]
The Python DC lessons don't get run all that often. I might run them in Feb, but mostly use them for onboarding undergraduates, which is somewhat of a structureless activity. We don't have a great sense of how long the materials actually take to get through, so we don't have a real basis to provide those estimates. Sometime soon, a series of blog posts should go up on why we teach what we teach. In that post, I ask for people who are/have/will teach the python stuff to get in touch so we can collect some data on how long things took.  So hopefully that's something we can know in the near future.

**Comment by barrachri** [comment]
I see, I will follow the discussion :)

**Comment by tracykteal** [comment]
Thanks @barrachri for this point. There is now an order of the lessons on the main page (http://www.datacarpentry.org/python-ecology-lesson/) and issue https://github.com/datacarpentry/python-ecology-lesson/issues/138 is for adding timing to the lessons, so that will create the schedule. 

So, I'm going to close this issue and point to the specific one about adding timing.
